#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#source /Users/chrism/.pyenv/versions/2.7.9/bin/activate.sh
#export PATH="/Users/chrism/anaconda/bin:$PATH"
#if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/conda-zsh-completion/_conda" ]]; then
#	fpath+="${ZDOTDIR:-$HOME}/.zprezto/modules/conda-zsh-completion"
#	compinit conda
#fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
