#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Customize to your needs...
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
#export PATH="/Users/chrism/anaconda/bin:$PATH"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/conda-zsh-completion/_conda" ]]; then
	fpath+="${ZDOTDIR:-$HOME}/.zprezto/modules/conda-zsh-completion"
	compinit conda
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
